version: "3.9"
services:
  mongodb:
    image: mongo:5.0.24
    volumes:
      - mongodata:/data/db
    expose:
      - "27017"
    ports:
      - "27017:27017"
  api-server:
    build:
      context: .
    depends_on:
      - mongodb
    expose:
      - "8443"
    ports:
      - "12078:8443"
    environment:
      # Secrets below - pass through (populate with `. ./devSecrets.sh`)
      - BROADCAST_ENGINE_PUBNUB_BLUE_KEY_PUBLISH_KEY
      - BROADCAST_ENGINE_PUBNUB_BLUE_KEY_SECRET_KEY
      - BROADCAST_ENGINE_PUBNUB_BLUE_KEY_SUBSCRIBE_KEY
      - BROADCAST_ENGINE_PUBNUB_GREEN_KEY_PUBLISH_KEY
      - BROADCAST_ENGINE_PUBNUB_GREEN_KEY_SECRET_KEY
      - BROADCAST_ENGINE_PUBNUB_GREEN_KEY_SUBSCRIBE_KEY
      - EMAIL_DELIVERY_SENDGRID_APIKEY
      - ENVIRONMENT_GROUP_SECRETS_REQUEST_AUTH
      - INTEGRATIONS_ASANA_CLOUD_APP_CLIENT_ID
      - INTEGRATIONS_ASANA_CLOUD_APP_CLIENT_SECRET
      - INTEGRATIONS_BITBUCKET_CLOUD_APP_CLIENT_ID
      - INTEGRATIONS_BITBUCKET_CLOUD_APP_CLIENT_SECRET
      - INTEGRATIONS_DEVOPS_CLOUD_APP_CLIENT_ID
      - INTEGRATIONS_DEVOPS_CLOUD_APP_CLIENT_SECRET
      - INTEGRATIONS_GITHUB_CLOUD_APP_CLIENT_ID
      - INTEGRATIONS_GITHUB_CLOUD_APP_CLIENT_SECRET
      - INTEGRATIONS_GITLAB_CLOUD_APP_CLIENT_ID
      - INTEGRATIONS_GITLAB_CLOUD_APP_CLIENT_SECRET
      - INTEGRATIONS_JIRA_CLOUD_APP_CLIENT_ID
      - INTEGRATIONS_JIRA_CLOUD_APP_CLIENT_SECRET
      - INTEGRATIONS_LINEAR_CLOUD_APP_CLIENT_ID
      - INTEGRATIONS_LINEAR_CLOUD_APP_CLIENT_SECRET
      - INTEGRATIONS_MSTEAMS_CLOUD_APP_CLIENT_ID
      - INTEGRATIONS_MSTEAMS_CLOUD_APP_CLIENT_SECRET
      - INTEGRATIONS_MSTEAMS_CLOUD_BOT_APP_ID
      - INTEGRATIONS_MSTEAMS_CLOUD_BOT_APP_PASSWORD
      - INTEGRATIONS_NEW_RELIC_IDENTITY_CLOUD_NEW_RELIC_CLIENT_ID
      - INTEGRATIONS_NEW_RELIC_IDENTITY_CLOUD_NEW_RELIC_CLIENT_SECRET
      - INTEGRATIONS_NEW_RELIC_IDENTITY_CLOUD_PASSWORD_KEY
      - INTEGRATIONS_NEW_RELIC_IDENTITY_CLOUD_USER_SERVICE_SECRET
      - INTEGRATIONS_NEWRELIC_CLOUD_ACCOUNT_NUMBER
      - INTEGRATIONS_NEWRELIC_CLOUD_BROWSER_INGEST_KEY
      - INTEGRATIONS_NEWRELIC_CLOUD_LICENSE_INGEST_KEY
      - INTEGRATIONS_NEWRELIC_CLOUD_TELEMETRY_ENDPOINT
      - INTEGRATIONS_NEWRELIC_CLOUD_WEBVIEW_AGENT_ID
      - INTEGRATIONS_NEWRELIC_CLOUD_WEBVIEW_APP_ID
      - INTEGRATIONS_NEWRELICGROK_CLOUD_API_KEY
      - INTEGRATIONS_SLACK_CLOUD_APP_CLIENT_ID
      - INTEGRATIONS_SLACK_CLOUD_APP_CLIENT_SECRET
      - INTEGRATIONS_SLACK_CLOUD_APP_ID
      - INTEGRATIONS_SLACK_CLOUD_APP_SIGNING_SECRET
      - INTEGRATIONS_TRELLO_CLOUD_APP_CLIENT_ID
      - TELEMETRY_SEGMENT_TOKEN
      - TELEMETRY_SEGMENT_WEB_TOKEN
      - UNIVERSAL_SECRETS_TELEMETRY
volumes:
  mongodata:
    driver: local
