'use strict';

module.exports = [
	'012mail.net', '123-email.com', '126.com', '163.com', '194.152.104.5', '196.36.153.112',
	'200.196.233.47', '60gp.ovh.net', '8-0.net', 'abed.vimail.com.br', 'adelphia.net',
	'africa-11.com', 'ahoo.com', 'aim.com', 'ajato.com.br', 'alex.lu', 'aliasmail.de',
	'allin1.com', 'america.hm', 'amr.mail.accenture.com', 'amuro.net', 'anonymous.to',
	'anymail.kify.com', 'aol.com', 'aolchat.fr', 'aolmail.aol.com.br', 'apennootje.nl',
	'apexmail.com', 'aracer.com', 'aspemail.com', 'asurfer.com', 'atenista.net', 'att.net',
	'ausi.com', 'authmail.brturbo.com.br', 'authmail.ibest.com.br', 'authmail.ig.com.br',
	'bahu.com', 'belizemail.net', 'bellsouth.net', 'bigfoot.com', 'bigpond.com', 'bigpond.net.au',
	'bigstring.com', 'bimamail.com', 'blogs.rediff.com', 'bluebottle.com', 'bogyoka.hu',
	'bol.com.br', 'bol.uol.com.br', 'bolond.hu', 'box.punkt.pl', 'br.ibm.com', 'br.inter.net',
	'breakthru.com', 'brfree.com.br', 'broadcastemailingagency.com', 'brturbo.com', 'brturbo.com.br',
	'btinternet.com', 'buzzlemail.com', 'c2.hu', 'caramail.com', 'caramail.lycos.fr',
	'cartman.hu', 'cartooners.com', 'cbn.net.id', 'cc.utulsa.edu', 'ccnmail.com', 'centrin.net.id',
	'centroin.com.br', 'charter.net', 'chat.free.fr', 'chatfuggo.hu', 'checkyouremail.co.uk',
	'chief.hu', 'chooseyourmail.com', 'christianmail.net', 'citigroup.com', 'citromail.hu',
	'citrommail.hu', 'city10.com.br', 'classicalwebcast.com', 'click21.com.br', 'coldmail.com',
	'coldmail.nu', 'comcast.net', 'commcenter.bresnan.net', 'cooljakarta.com', 'coolrio.com',
	'coolyork.com', 'copticmail.com', 'correio.upis.br', 'correo.juntadeandalucia.es',
	'cox.net', 'cs.com', 'dejanews.com', 'directnet.com.br', 'dmailman.com', 'doramail.com',
	'dwmail.net', 'e-messenger.net', 'earthlink.net', 'easymail.hu', 'ecomail.org', 'edsamail.com.ph',
	'educationmail.net', 'email.2000net.com', 'email.37.com', 'email.accountsupport.com',
	'email.azet.sk', 'email.bestdresses.com', 'email.com', 'email.com.br', 'email.cz',
	'email.excite.com', 'email.internet.lu', 'email.it', 'email.luxweb.com', 'email.ro',
	'email.ru', 'email.secureserver.net', 'email.seznam.cz', 'email.si', 'email.uol.com.br',
	'email2me.net', 'emailaddresses.com', 'emailasso.net', 'emailman.com', 'emailme.nu',
	'emails-mail.nouvelobs.com', 'emailsites.tripod.com', 'emailsreview.com', 'emil.hu',
	'epost.cz', 'estadao.com.br', 'eudoramail.com', 'everymail.net', 'everyone.net',
	'excite.com', 'extranet.hu', 'f1mail.rediff.com', 'f2mail.rediff.com', 'f3mail.rediff.com',
	'fastmail.ca', 'fastmail.fm', 'fepg.net', 'findmemail.com', 'flash.ro', 'flashemail.com',
	'flashmail.club-internet.fr', 'flashmail.clubinternet.fr', 'flashmail.com', 'forevermail.com',
	'francemel.com', 'francemel.fr', 'free-email-address.com', 'free.fr', 'free.os.pl',
	'free.za-mail.de', 'freemail.2cool.net', 'freemail.aussiemail.com.au', 'freemail.hu',
	'freemail.org.mk', 'freemail.web.de', 'freemailguide.com', 'freestart.hu', 'freestuffchannel.com',
	'freetibet.hu', 'friend.ly.net', 'friends.walla.co.il', 'funnymail.com', 'gamania.com',
	'garrison.hu', 'gawab.com', 'getemail.sympatico.ca', 'getresponse.com', 'globalmail.net.il',
	'globo.com', 'gmail.com', 'gmail.google.com', 'gmail.ru', 'gmx.de', 'gmx.net', 'go.icq.com',
	'gomailus.go.com', 'graffiti.net', 'hanmail.net', 'hellobello.hu', 'hellokitty.com',
	'home.se', 'hot.ee', 'hotbox.ru', 'hotdak.net', 'hotmai.com', 'hotmail.co.uk', 'hotmail.com',
	'hotmail.com.br', 'hotmail.fr', 'hotmail.it', 'hotmail.msn.com', 'hotpop.com', 'ibest.com.br',
	'ibestmail.ibest.com.br', 'ibestvip.com.br', 'icqmail.com', 'ig.com.br', 'iinet.net.au',
	'ilema.net', 'imail.hu', 'imailreader.com', 'imap.ch', 'imo.im', 'imp.bambouweb.fr',
	'imp.free.fr', 'imp3-a.free.fr', 'imp4.free.fr', 'iname.ru', 'inbox.com', 'inbox.com.pk',
	'inbox.lv', 'inbox.ru', 'incisive-research.ec-messenger.com', 'indosat.net.id', 'infolink.com.br',
	'inmail.cz', 'inmail.sk', 'intel.com', 'iol.pt', 'ircfuggo.hu', 'iscooler.com', 'itelefonica.com.br',
	'jabble.com', 'jemimi.net', 'jmail.co.za', 'juno.com', 'kayamail.co.za', 'kenny.hu',
	'keromail.com', 'kyle.hu', 'lamessagerie.com', 'laposte.net', 'lavacheautomatique.com',
	'lemel.com', 'lemel.fr', 'leonlai.net', 'libero.it', 'liberomail.libero.it', 'like.com',
	'live.com', 'locoseek.com', 'login.live.com', 'login.passport.net', 'login.yahoo.com',
	'loginnet.passport.com', 'londonnetmail.com', 'loser.hu', 'lovecat.com', 'loveemail.com',
	'lovemail.co.uk', 'lycos.com', 'lycosemail.com', 'mabber.com', 'mac.com', 'macbox.com',
	'mackenzie.com.br', 'macvillage.net', 'mail.163.com', 'mail.3dup.com', 'mail.al-islam.com',
	'mail.aldar.net', 'mail.alice.it', 'mail.ananzi.co.za', 'mail.atlas.cz', 'mail.atlas.sk',
	'mail.be', 'mail.chek.com', 'mail.cityofcarrollton.com', 'mail.com', 'mail.danworld.com',
	'mail.dogomania.com', 'mail.emich.edu', 'mail.excite.com', 'mail.forum.dk', 'mail.funs.co.uk',
	'mail.gala.net', 'mail.gjj.cc', 'mail.globo.com', 'mail.go.com', 'mail.google.com',
	'mail.hellokitty.com', 'mail.hendon.com', 'mail.hitthebeach.com', 'mail.iinet.net.au',
	'mail.internet.lu', 'mail.leonardo.it', 'mail.live.com', 'mail.lv', 'mail.lycos.com',
	'mail.marcoreis.net', 'mail.masini.ro', 'mail.md', 'mail.med.umich.edu', 'mail.naseej.com',
	'mail.rambler.ru', 'mail.ru', 'mail.serverart.org', 'mail.sina.com.cn', 'mail.sogou.com',
	'mail.spancity.com', 'mail.spbnit.ru', 'mail.srmg.com', 'mail.srpc.com', 'mail.stockstorm.com',
	'mail.surftec.com', 'mail.t-email.hu', 'mail.teenmusic.com', 'mail.terra.com.br',
	'mail.thingfind.com', 'mail.tiscali.it', 'mail.tj', 'mail.tut.by', 'mail.ubbi.com',
	'mail.ubbi.com.br', 'mail.voila.fr', 'mail.volny.cz', 'mail.walla.com', 'mail.webone.com.au',
	'mail.yahoo.com', 'mail.yahoo.fr', 'mail.yandex.ru', 'mail.zoznam.sk', 'mail001.8800.org',
	'mail1.voila.fr', 'mail2.voila.fr', 'mail2go.com', 'mail2web.com', 'mail2world.com',
	'mail3.voila.fr', 'mail386.com', 'mailbell.com', 'mailbox-ag.de', 'mailbox.hu', 'mailcenter.comcast.net',
	'mailcenter2.comcast.net', 'mailcity.com', 'mailgate.ru', 'mailhost2.mana.pf', 'mailjolt.com',
	'mailrr.aruba.it', 'mandic.com.br', 'marchmail.com', 'mebwail.bur.st', 'meebo.com',
	'members.rediff.com', 'messagerie-13.sfr.fr', 'messagerie.sfr.fr', 'messagingsuite.orange.fr',
	'messenger.yahoo.com', 'messengerfx.com', 'mi-mail.cl', 'minutemails.com', 'mollymail.com',
	'moviesbymail.com', 'msn.com', 'msn2go.com', 'msoworld.com', 'muchomail.com', 'my.myway.com',
	'my.screenname.aol.com', 'my.yahoo.com', 'mycampus.phoenix.edu', 'myemail.com', 'mymail01.hellokitty.com',
	'mymelody.com', 'mynet.com', 'myrealbox.com', 'myself.com', 'mysg.8m.com', 'myway.com',
	'nectarine.it', 'netaddress.usa.net', 'netalfa.net', 'netcabo.pt', 'netcourrier.com',
	'netfuggo.hu', 'netmail.verizon.net', 'netmymail.com', 'netposta.net', 'netscape.net',
	'netvigator.com', 'netzero.com', 'netzero.net', 'neuromancer.hu', 'newmail.walla.co.il',
	'nom-prenom.com', 'norikomail.com', 'np.hu', 'ntlworld.com', 'nus.edu.sg', 'oi.com.br',
	'oimail.oi.com.br', 'onda.com.br', 'onebox.com', 'openlink.com.br', 'operamail.com',
	'optonline.net', 'optusnet.com.au', 'orangeday.net', 'orkut.com', 'orkut.com.br',
	'otmail.com', 'oumail.ou.edu', 'outlook.com', 'pacific.net.sg', 'pandamail.net',
	'pd.jaring.my', 'pee-mail.com', 'petrobras.com.br', 'pinoymail.com', 'plasa.com',
	'pldtdsl.net', 'pobox.com', 'pobox.sk', 'pochta.ru', 'pochta.ws', 'poczta.gazeta.pl',
	'poczta.interia.pl', 'poczta.neo.pl', 'poczta.o2.pl', 'poczta.onet.pl', 'poczta.prokocim.org',
	'poczta.szkola.tpi.pl', 'poczta.unet.pl', 'poczta.wp.pl', 'poczta04.o2.pl', 'pokemates.com',
	'poli.usp.br', 'pop.com.br', 'pop.postan.com', 'pop.suaturma.com', 'poppymail.com',
	'portoweb.com.br', 'portugalmail.pt', 'post.cz', 'post.ro', 'post.sk', 'postino.ch',
	'predialnet.com.br', 'prontomail.com', 'psi.dynegy.com', 'qmail.com', 'quickemail.de',
	'rediffmail.com', 'rette.net', 'rjnet.com.br', 'rock.com', 'rocketmail.com', 'rogers.com',
	's-mail.com', 'sapo.pt', 'sbcglobal.net', 'sendmail.cz', 'shaw.ca', 'sihu.hu', 'sina.com',
	'sinagirl.com', 'sinaman.com', 'singapore.com', 'singnet.com', 'singnet.com.sg',
	'smootch.com', 'smoove.org', 'softhome.net', 'spymac.com', 'staffmail.ecu.edu.au',
	'stan.hu', 'starhub.net.sg', 'startadsl.hu', 'startmail.hu', 'streamyx.com', 'superig.com.br',
	'superonline.com', 'surimail.com', 'survivormail.com', 'swissmail.net', 'sympatico.ca',
	'szigetlako.hu', 'tangolive.tango.lu', 'techemail.com', 'telkom.net', 'telus.net',
	'terra.com.br', 'thedoghousemail.com', 'thnx.hu', 'time.net.my', 'tm.net.my', 'tv2mail.hu',
	'ua.fm', 'uai.com.br', 'ubbi.com.br', 'ublaze.com', 'ueberschuss.de', 'ukr.net',
	'uol.com.br', 'up.edu.ph', 'us.rediff.com', 'usa.com', 'usp.br', 'velnet.biz', 'veloxmail.com.br',
	'verizon.net', 'via-rs.net', 'vipmail.hu', 'walla.com', 'wanadoo.fr', 'wayn.com',
	'web-mail.chello.hu', 'web-mail.chello.pl', 'web.de', 'web.mail.demon.net', 'webbasedemail.com',
	'webemails.com', 'webemil.de', 'webescape.com', 'webmail.absamail.co.za', 'webmail.acecoti.com.br',
	'webmail.adelphia.net', 'webmail.adrianasantana.ntr.br', 'webmail.advancecontabilidade.com.br',
	'webmail.air.defense.gouv.fr', 'webmail.aliceadsl.fr', 'webmail.all-inkl.com', 'webmail.ambr.com.br',
	'webmail.animesko.com.br', 'webmail.aol.com', 'webmail.aon.at', 'webmail.apis.com.br',
	'webmail.arach.net.au', 'webmail.arquivogospel.com.br', 'webmail.artelecom.pt', 'webmail.aruba.it',
	'webmail.atarde.com.br', 'webmail.atelecom.com.br', 'webmail.bearingpoint.com', 'webmail.bermudes.com.br',
	'webmail.bke.hu', 'webmail.bluefrog.com', 'webmail.botafogonocoracao.net', 'webmail.brasiltlecom.com.br',
	'webmail.brtdata.com.br', 'webmail.brturbo.com.br', 'webmail.bur.st', 'webmail.bynet.ca',
	'webmail.cabonet.com.br', 'webmail.cabovisao.pt', 'webmail.capitalservicos.com.br',
	'webmail.cardiol.br', 'webmail.central.cox.net', 'webmail.chello.hu', 'webmail.chello.pl',
	'webmail.cidadeinternet.com.br', 'webmail.citycable.ch', 'webmail.clix.pt', 'webmail.cni.org.br',
	'webmail.co.za', 'webmail.codevasf.gov.br', 'webmail.cogeco.ca', 'webmail.conectanet.com.br',
	'webmail.corpservice.com.br', 'webmail.correios.net.br', 'webmail.correioweb.com.br',
	'webmail.cosmopolita.com.br', 'webmail.costabarros.com', 'webmail.covad.net', 'webmail.covansys.com',
	'webmail.curingapneus.com.br', 'webmail.cvbb.org.br', 'webmail.datanet.hu', 'webmail.dial-up.net',
	'webmail.digidoc.com.br', 'webmail.dnet.it', 'webmail.easynet.ro', 'webmail.elkrapidsnet.com',
	'webmail.elnet.com.br', 'webmail.estadao.com.br', 'webmail.externet.hu', 'webmail.facitec.br',
	'webmail.faculdadejk.com.br', 'webmail.free.fr', 'webmail.globo.com', 'webmail.green.ch',
	'webmail.grv.art.br', 'webmail.hostlocation.com.br', 'webmail.hostsys.com.br', 'webmail.ibest.com.br',
	'webmail.ig.com.br', 'webmail.igempresas.ig.com.br', 'webmail.influxbrasil.com',
	'webmail.infomaniak.ch', 'webmail.integrity.hu', 'webmail.inteligweb.com.br', 'webmail.iol.pt',
	'webmail.ipartners.pl', 'webmail.iphan.gov.br', 'webmail.iprimus.com.au', 'webmail.isbt.terra.com.br',
	'webmail.juno.com', 'webmail.klg.nl', 'webmail.klg.nu', 'webmail.konta.pl', 'webmail.kpnqwest.pt',
	'webmail.lacazmartins.com.br', 'webmail.lao.net', 'webmail.lesaem.org', 'webmail.linkdata.com.br',
	'webmail.linkexpress.com.br', 'webmail.localnet.com', 'webmail.localnet.net', 'webmail.matrix.com.br',
	'webmail.mcraews.com', 'webmail.mec.gov.br', 'webmail.mg.trt.gov.br', 'webmail.mgp.neufgp.fr',
	'webmail.miemail.cl', 'webmail.mmuc.com.br', 'webmail.murdoch.edu.au', 'webmail.myregisteredsite.com',
	'webmail.neostrada.pl', 'webmail.netcabo.pt', 'webmail.netvisao.pt', 'webmail.networld.psi.br',
	'webmail.neuf.fr', 'webmail.nomer.com.br', 'webmail.novis.pt', 'webmail.numericable.fr',
	'webmail.odn.de', 'webmail.oi.com.br', 'webmail.oni.pt', 'webmail.oninet.pt', 'webmail.orange.fr',
	'webmail.orolix.com.br', 'webmail.ovh.net', 'webmail.pakiet24.pl', 'webmail.pas.earthlink.net',
	'webmail.pedacinhoweb.com.br', 'webmail.people.net.au', 'webmail.peoplepc.com', 'webmail.phg.ro',
	'webmail.planejamento.gov.br', 'webmail.plugin.com.br', 'webmail.polytech-lille.fr',
	'webmail.posta.tim.it', 'webmail.pregadoresdotelhado.org.br', 'webmail.pressa.com.br',
	'webmail.proanima.org.br', 'webmail.prodigy.net.mx', 'webmail.pt', 'webmail.pt.lu',
	'webmail.ramalhopires.com.br', 'webmail.rudah.com.br', 'webmail.rulezmail.hu', 'webmail.runway.com.br',
	'webmail.sapo.pt', 'webmail.services.hu', 'webmail.shaw.ca', 'webmail.sofast.net',
	'webmail.sso.bluewin.ch', 'webmail.stbdsn.com.br', 'webmail.swiftel.com.au', 'webmail.tele2.at',
	'webmail.tele2.ch', 'webmail.tele2.fr', 'webmail.telepac.pt', 'webmail.telkomsa.net',
	'webmail.telus.net', 'webmail.thai.com', 'webmail.tiscali.fr', 'webmail.torchlake.com',
	'webmail.tostoadv.com', 'webmail.tpi.pl', 'webmail.tvnet.hu', 'webmail.tvnetwork.hu',
	'webmail.tvtel.pt', 'webmail.uai.com.br', 'webmail.umd.umich.edu', 'webmail.unb.br',
	'webmail.unibanco.com.br', 'webmail.unicredsys.com.br', 'webmail.unip.br', 'webmail.us.army.mil',
	'webmail.valvision.fr', 'webmail.via-rs.com.br', 'webmail.via-rs.net', 'webmail.vip.tpi.pl',
	'webmail.vol.at', 'webmail.wanadoo.fr', 'webmail.zdoisz.com.br', 'webmail.zpok.hu',
	'webmail1.click21.com.br', 'webmail1.educacional.com.br', 'webmail2.brte.com.br',
	'webmail2.brturbo.com', 'webmail2.click21.com.br', 'webmail2.cni.org.br', 'webmail3.click21.com.br',
	'webmail4.click21.com.br', 'webmail5.click21.com.br', 'webmail6.click21.com.br',
	'webmail7.click21.com.br', 'webmail8.click21.com.br', 'webmailb.juno.com', 'webmaildominiold.aruba.it',
	'webmailer.1und1.de', 'webmailold.ibest.com.br', 'webmailold.ig.com.br', 'webmessenger.msn.com',
	'webmessenger.yahoo.com', 'webvodafonemail.vodafone.pt', 'wiccanmail.com', 'wmail.dial-up.net',
	'wnetrj.com.br', 'worldemail.com', 'www4mail.org', 'xanga.com', 'xasamail.com', 'xekmail.aeiou.pt',
	'xmail.net', 'xs2mail.com', 'xtra.co.nz', 'xtramail.xtra.co.nz', 'yaho.com', 'yahoo.ca',
	'yahoo.co.id', 'yahoo.co.in', 'yahoo.co.jp', 'yahoo.co.nz', 'yahoo.co.uk', 'yahoo.com',
	'yahoo.com.ar', 'yahoo.com.au', 'yahoo.com.br', 'yahoo.com.cn', 'yahoo.com.hk', 'yahoo.com.hktmail.com',
	'yahoo.com.mx', 'yahoo.com.my', 'yahoo.com.ph', 'yahoo.com.sg', 'yahoo.com.sgl.com',
	'yahoo.com.tw', 'yahoo.de', 'yahoo.es', 'yahoo.fr', 'yahoo.it', 'yahoogroups.com',
	'yehey.com', 'yhoo.com', 'ymail.com', 'yopmail.com', 'your-mail.com', 'your.hispeed.ch',
	'yousendit.com', 'zimbra.aliceadsl.fr', 'zimbra.free.fr', 'zipmail.com.br', 'zipmail.uol.com.br',
	'me.com', 'icloud.com', 'hotmail.ca', 'unseen.is', 'googlemail.com', 'yandex.ru', 'sonic.net',
	'live.co.uk', 't-online.de', 'telenet.be', 'eastlink.ca', 'gmx.com', 'vivaldi.net', 'exemail.com.au',
	'seznam.cz', 'q.com', '123mail.org', 'airpost.net', 'eml.cc', 'fmail.co.uk', 'fmgirl.com', 'fmguy.com',
	'mailbolt.com', 'mailcan.com', 'mailhaven.com', 'mailmight.com', 'ml1.net', 'mm.st', 'myfastmail.com',
	'proinbox.com', 'promessage.com', 'rushpost.com', 'sent.as', 'sent.at', 'sent.com', 'speedymail.org',
	'warpmail.net', 'xsmail.com', '150mail.com', '150ml.com', '16mail.com', '2-mail.com', '4email.net',
	'50mail.com', 'allmail.net', 'bestmail.us', 'cluemail.com', 'elitemail.org', 'emailcorner.net',
	'emailengine.net', 'emailengine.org', 'emailgroups.net', 'emailplus.org', 'emailuser.net', 'f-m.fm',
	'fast-email.com', 'fast-mail.org', 'fastem.com', 'fastemail.us', 'fastemailer.com', 'fastest.cc',
	'fastimap.com', 'fastmailbox.net', 'fastmessaging.com', 'fea.st', 'fmailbox.com', 'ftml.net',
	'h-mail.us', 'hailmail.net', 'imap-mail.com', 'imap.cc', 'imapmail.org', 'inoutbox.com',
	'internet-e-mail.com', 'internet-mail.org', 'internetemails.net', 'internetmailing.net',
	'jetemail.net', 'justemail.net', 'letterboxes.org', 'mail-central.com', 'mail-page.com',
	'mailandftp.com', 'mailas.com', 'mailc.net', 'mailforce.net', 'mailftp.com', 'mailingaddress.org',
	'mailite.com', 'mailnew.com', 'mailsent.net', 'mailservice.ms', 'mailup.net', 'mailworks.org',
	'mymacmail.com', 'nospammail.net', 'ownmail.net', 'petml.com', 'postinbox.com', 'postpro.net',
	'realemail.net', 'reallyfast.biz', 'reallyfast.info', 'speedpost.net', 'ssl-mail.com',
	'swift-mail.com', 'the-fastest.net', 'the-quickest.com', 'theinternetemail.com', 'veryfast.biz',
	'veryspeedy.net', 'yepmail.net', 'your-mail.com', 'bluewin.ch', 'gmx.ch', 'opayq.com', 'online.no',
	'yandex.com', 'mail.yandex.com', 'arcor.de', 'btopenworld.com', 'mindspring.com'
];
