// handle unit tests for the "POST /posts" request

'use strict';

const PostToChannelTest = require('./post_to_channel_test');
const PostToDirectTest = require('./post_to_direct_test');
const ItemTest = require('./item_test');
const ItemMarkerTest = require('./item_marker_test');
const ExistingFileStreamTest = require('./existing_file_stream_test');

/*
const PostToFileStreamTest = require('./post_to_file_stream_test');
const MarkerTest = require('./marker_test');
const NoCommitHashTest = require('./no_commit_hash_test');
const NoCommitHashWithFileTest = require('./no_commit_hash_with_file_test');
const NoCommitHashWithStreamTest = require('./no_commit_hash_with_stream_test');
const MarkersNotArrayTest = require('./markers_not_array_test');
const MarkersTooLongTest = require('./markers_too_long_test');
const MarkerNotObjectTest = require('./marker_not_object_test');
const MarkerTooBigTest = require('./marker_too_big_test');
const CodeMustBeStringTest = require('./code_must_be_string_test');
const NoCodeTest = require('./no_code_test');
const PreContextMustBeStringTest = require('./pre_context_must_be_string_test');
const PostContextMustBeStringTest = require('./post_context_must_be_string_test');
const InvalidFileTest = require('./invalid_file_test');
const LocationMustBeArrayTest = require('./location_must_be_array_test');
const LocationTooLongTest = require('./location_too_long_test');
const LocationTooShortTest = require('./location_too_short_test');
const LocationMustBeNumbersTest = require('./location_must_be_numbers_test');
const RemotesMustBeArrayTest = require('./remotes_must_be_array_test');
const RemotesMustBeArrayOfStringsTest = require('./remotes_must_be_array_of_strings_test');
const TooManyRemotesTest = require('./too_many_remotes_test');
const InvalidCoordinateObjectTest = require('./invalid_coordinate_object_test');
const NoLocationOkTest = require('./no_location_ok_test');
const MarkerHasInvalidStreamIdTest = require('./marker_has_invalid_stream_id_test');
const MarkerHasImproperAttributesTest = require('./marker_has_improper_attributes_test');
const MarkerHasUnknownStreamIdTest = require('./marker_has_unknown_stream_id_test');
const MarkerForBadStreamTypeTest = require('./marker_for_bad_stream_type_test');
const MarkerFromDifferentTeamTest = require('./marker_from_different_team_test');
const MarkerStreamOnTheFly = require('./marker_stream_on_the_fly_test');
const FindRepoByRemotesTest = require('./find_repo_by_remotes_test');
const UpdateMatchedRepoWithRemotesTest = require('./update_matched_repo_with_remotes_test');
const UpdateSetRepoWithRemotesTest = require('./update_set_repo_with_remotes_test');
const CreateRepoOnTheFlyTest = require('./create_repo_on_the_fly_test');
const NumMarkersTest = require('./num_markers_test');
const MarkerFromDifferentStreamTest = require('./marker_from_different_stream_test');
const PostReplyTest = require('./post_reply_test');
const NoStreamIdTest = require('./no_stream_id_test');
const InvalidStreamIdTest = require('./invalid_stream_id_test');
const DirectOnTheFlyTest = require('./direct_on_the_fly_test');
const ChannelOnTheFlyTest = require('./channel_on_the_fly_test');
const FileStreamOnTheFlyTest = require('./file_stream_on_the_fly_test');
const InvalidRepoIdTest = require('./invalid_repo_id_test');
const NoStreamAttributeTest = require('./no_stream_attribute_test');
const InvalidTeamIdTest = require('./invalid_team_id_test');
const DuplicateChannelTest = require('./duplicate_channel_test');
const DuplicateDirectTest = require('./duplicate_direct_test');
const DuplicateFileStreamTest = require('./duplicate_file_stream_test');
const InvalidTypeTest = require('./invalid_type_test');
const NoTypeTest = require('./no_type_test');
const InvalidPrivacyTest = require('./invalid_privacy_test');
const MeDirectTest = require('./me_direct_test');
const MeChannelTest = require('./me_channel_test');
const NameRequiredTest = require('./name_required_test');
const NoFileTest = require('./no_file_test');
const TeamStreamMustBeChannelTest = require('./team_stream_must_be_channel_test');
const NoRepoIdTest = require('./no_repo_id_test');
const NoTeamIdTest = require('./no_team_id_test');
const ACLTeamTest = require('./acl_team_test');
const ACLStreamTest = require('./acl_stream_test');
const ACLTeamOnTheFlyTest = require('./acl_team_on_the_fly_test');
const NewPostMessageToTeamTest = require('./new_post_message_to_team_test');
const NewPostMessageToTeamStreamTest = require('./new_post_message_to_team_stream_test');
const NewPostMessageToChannelTest = require('./new_post_message_to_channel_test');
const NewPostMessageToDirectTest = require('./new_post_message_to_direct_test');
const NewPostNoMessageToChannelTest = require('./new_post_no_message_to_channel_test');
const NewPostNoMessageToDirectTest = require('./new_post_no_message_to_direct_test');
const NewFileStreamMessageToTeamTest = require('./new_file_stream_message_to_team_test');
const NewMarkerStreamMessageToTeamTest = require('./new_marker_stream_message_to_team_test');
const NewTeamStreamMessageToTeamTest = require('./new_team_stream_message_to_team_test');
const NewChannelMessageToMembersTest = require('./new_channel_message_to_members_test');
const NewDirectMessageToMembersTest = require('./new_direct_message_to_members_test');
const NewRepoMessageToTeamTest = require('./new_repo_message_to_team_test');
const UpdatedSetRepoMessageTest = require('./updated_set_repo_message_test');
const UpdatedMatchedRepoMessageTest = require('./update_matched_repo_message_test');
const MostRecentPostTest = require('./most_recent_post_test');
const LastReadsNoneTest = require('./last_reads_none_test');
const NoLastReadsForAuthorTest = require('./no_last_reads_for_author_test');
const LastReadsPreviousPostTest = require('./last_reads_previous_post_test');
const NoLastReadsUpdateTest = require('./no_last_reads_update_test');
const SeqNumTest = require('./seqnum_test');
const StreamOnTheFlySeqNumTest = require('./stream_on_the_fly_seqnum_test');
const NumCommentsTest = require('./num_comments_test');
const NumCommentsMessageTest = require('./num_comments_message_test');
const MentionTest = require('./mention_test');
const UnregisteredMentionTest = require('./unregistered_mention_test');
const MessageToAuthor = require('./message_to_author_test');
const SetPersonAnalyticsTest = require('./set_person_analytics_test');
const OnTheFlyMarkerStreamFromDifferentTeamTest = require('./on_the_fly_marker_stream_from_different_team_test');
const OnTheFlyMarkerStreamRepoNotFoundTest = require('./on_the_fly_marker_stream_repo_not_found_test');
const OnTheFlyMarkerStreamNoRepoIdTest = require('./on_the_fly_marker_stream_no_repo_id_test');
const OnTheFlyMarkerStreamInvalidRepoIdTest = require('./on_the_fly_marker_stream_invalid_repo_id_test');
const HasRepliesTest = require('./has_replies_test');
const SecondReplyTest = require('./second_reply_test');
const HasRepliesMessageToStreamTest = require('./has_replies_message_to_stream_test');
const NumRepliesMessageToStreamTest = require('./num_replies_message_to_stream_test');
const OriginFromPluginTest = require('./origin_from_plugin_test');
const ProviderPostTest = require('./provider_post_test');
*/

class PostPostRequestTester {

	postPostTest () {
		new PostToChannelTest().test();
		new PostToDirectTest().test();
		new ItemTest().test();
		new ItemMarkerTest().test();
		new ExistingFileStreamTest().test();
		/*
		//new PostToFileStreamTest().test();	// TODO: test this being prevented
		new MarkerTest().test();
		new MarkerFromDifferentStreamTest({ streamType: 'direct' }).test();
		new MarkerFromDifferentStreamTest({ streamType: 'channel' }).test();
		new MarkerFromDifferentStreamTest({ streamType: 'file' }).test();



		new NoCommitHashTest().test();
		new NoCommitHashWithFileTest().test();
		new NoCommitHashWithStreamTest().test();
		new MarkersNotArrayTest().test();
		new MarkersTooLongTest().test();
		new LocationTooShortTest().test();
		new MarkerNotObjectTest().test();
		new MarkerTooBigTest().test();
		new CodeMustBeStringTest().test();
		new NoCodeTest().test();
		new PreContextMustBeStringTest().test();
		new PostContextMustBeStringTest().test();
		new InvalidFileTest().test();
		new LocationMustBeArrayTest().test();
		new LocationTooLongTest().test();
		new LocationMustBeNumbersTest().test();
		new RemotesMustBeArrayTest().test();
		new RemotesMustBeArrayOfStringsTest().test();
		new TooManyRemotesTest().test();
		new InvalidCoordinateObjectTest().test();
		new NoLocationOkTest().test();
		new MarkerHasInvalidStreamIdTest().test();
		new MarkerHasImproperAttributesTest().test();
		new MarkerHasUnknownStreamIdTest().test();
		new MarkerForBadStreamTypeTest({ streamType: 'direct' }).test();
		new MarkerForBadStreamTypeTest({ streamType: 'channel' }).test();
		new MarkerFromDifferentTeamTest().test();
		new NumMarkersTest().test();
		new MarkerStreamOnTheFly({ streamType: 'direct' }).test();
		new MarkerStreamOnTheFly({ streamType: 'channel' }).test();
		new MarkerStreamOnTheFly({ streamType: 'file' }).test();
		new FindRepoByRemotesTest().test();
		new UpdateMatchedRepoWithRemotesTest().test();
		new UpdateSetRepoWithRemotesTest().test();
		new CreateRepoOnTheFlyTest().test();
		new PostReplyTest().test();
		new NoStreamIdTest().test();
		new InvalidStreamIdTest().test();
		new DirectOnTheFlyTest().test();
		new ChannelOnTheFlyTest().test();
		new FileStreamOnTheFlyTest().test();
		new InvalidRepoIdTest().test();
		new NoStreamAttributeTest({ attribute: 'teamId' }).test();
		new NoStreamAttributeTest({ attribute: 'type' }).test();
		new InvalidTeamIdTest().test();
		new DuplicateChannelTest().test();
		new DuplicateDirectTest().test();
		new DuplicateFileStreamTest().test();
		new InvalidTypeTest().test();
		new NoTypeTest().test();
		new InvalidPrivacyTest().test();
		new MeDirectTest().test();
		new MeChannelTest().test();
		new NameRequiredTest().test();
		new NoFileTest().test();
		new TeamStreamMustBeChannelTest().test();
		new NoRepoIdTest().test();
		new NoTeamIdTest().test();
		new ACLStreamTest().test();
		new ACLTeamTest().test();
		new ACLTeamOnTheFlyTest().test();
		new NewPostMessageToTeamTest().test();
		new NewPostMessageToTeamStreamTest().test();
		new NewPostMessageToChannelTest().test();
		new NewPostMessageToDirectTest().test();
		new NewPostNoMessageToChannelTest().test();
		new NewPostNoMessageToDirectTest().test();
		new NewFileStreamMessageToTeamTest().test();
		new NewMarkerStreamMessageToTeamTest().test();
		new NewTeamStreamMessageToTeamTest().test();
		new NewChannelMessageToMembersTest().test();
		new NewDirectMessageToMembersTest().test();
		new NewRepoMessageToTeamTest().test();
		new UpdatedSetRepoMessageTest().test();
		new UpdatedMatchedRepoMessageTest().test();
		new MostRecentPostTest().test();
		new LastReadsNoneTest({ type: 'direct' }).test();
		new LastReadsNoneTest({ type: 'channel' }).test();
		new LastReadsNoneTest({ type: 'file' }).test();
		new NoLastReadsForAuthorTest().test();
		new LastReadsPreviousPostTest({ type: 'direct' }).test();
		new LastReadsPreviousPostTest({ type: 'channel' }).test();
		new LastReadsPreviousPostTest({ type: 'file' }).test();
		new NoLastReadsUpdateTest().test();
		new SeqNumTest().test();
		new StreamOnTheFlySeqNumTest().test();
		new NumCommentsTest().test();
		new NumCommentsMessageTest().test();
		new HasRepliesTest().test();
		new SecondReplyTest().test();
		new HasRepliesMessageToStreamTest({ type: 'direct' }).test();
		new HasRepliesMessageToStreamTest({ type: 'channel' }).test();
		new NumRepliesMessageToStreamTest({ type: 'direct' }).test();
		new NumRepliesMessageToStreamTest({ type: 'channel' }).test();
		new MentionTest().test();
		new UnregisteredMentionTest().test();
		new MessageToAuthor().test();
		new SetPersonAnalyticsTest().test();
		new OnTheFlyMarkerStreamFromDifferentTeamTest().test();
		new OnTheFlyMarkerStreamRepoNotFoundTest().test();
		new OnTheFlyMarkerStreamNoRepoIdTest().test();
		new OnTheFlyMarkerStreamInvalidRepoIdTest().test();
		new OriginFromPluginTest().test();
		new ProviderPostTest().test();
		new ItemTest().test();
		new ItemMarkerTest().test();
		*/
	}
}

module.exports = PostPostRequestTester;
