#!/bin/bash

[ -z "$1" ] && echo "Do not run this script directly. Run dt-configure-sandbox instead." && exit 1

# argument:
#   configure         normal configuration mode. Run on a clean install or reconfigure (mode = configure)
#   git_hook          run from within a git hook (mode = git_hook)
#   deploy            run from within a deployment (dt-build)
#   configureNoAbort  configuration mode but don't abort early if there's a build failure (mode = configure)
mode=""
abort_on_fail=1
[ "$1" == "git-hook" ] && mode=git_hook
[ "$1" == "configure" ] && mode=configure
[ "$1" == "deploy" ] && mode=deploy
[ "$1" == "configureNoAbort" ] && mode=configure && abort_on_fail=0
[ -z "$mode" ] && echo "Error: bad configure mode" && exit 1

# This script is called as a hook (from dt-configure-sandbox, deployment script, git hook, ...).
# DO NOT CALL IT DIRECTLY.
#
# Place any commands needed to prepare the sandbox for use here. Assume the
# environment is set

# Specific to mono-repo
[ ! -d $OPADM_REPO_ROOT/.git ] && echo "nothing to configure for a pre-built asset sandbox" && exit 0
[ -f $OPADM_REPO_ROOT/.gitmodules ] && echo "updating submodules" && (cd $OPADM_REPO_ROOT && git submodule update --init --recursive)

cd $OPADM_TOP

# Exmaple: expanding templates
# $DT_TOP/bin/create-file-from-template.py -t $XYZ_SANDBOX/git_project/etc/httpd.conf.template -o $XYZ_SANDBOX/conf/httpd.conf

# If the sandbox uses node, wipe the node_modules and re-install during re-configuration
if [ -f $OPADM_TOP/package.json -a -n "$OPADM_NODE_VER" ]; then
	[ -d $OPADM_TOP/node_modules ] && /bin/rm -rf $OPADM_TOP/node_modules
	if [ "$OPADM_YARN" == true ]; then
		[ ! -f $OPADM_TOP/yarn.lock ] && echo "WARNING: yarn.lock not found - creating one"
		echo "yarn install (from `pwd`)"
		yarn install --frozen-lockfile
		[ $? -ne 0 ] && echo "yarn install failed" && [ $abort_on_fail -eq 1 ] && exit 1
	else
		echo "npm install --no-save (from `pwd`)"
		npm install --no-save
		[ $? -ne 0 ] && echo "npm install failed" && [ $abort_on_fail -eq 1 ] && exit 1
	fi
fi

# Optional NPM package integrity check
# To set this integrtity check up, you must manually create (and maintain) a file containing
# a list of packages whenever you make changes:
#    cd $OPADM_TOP
#    npm ls | grep -v ^CodeStream_Server@ >sandbox/package-versions.txt
#
#
# if [ -f sandbox/package-versions.txt ]; then
# 	tmpfile=/tmp/junk$$
# 	npm ls |grep -v ^CodeStream_Server@ >$tmpfile
# 	x=`diff sandbox/package-versions.txt $tmpfile|wc -l`
# 	if [ $x -gt 0 ]; then
# 		echo "***************************************************************************"
# 		echo "   ERROR: package tree looks different than sandbox/package-versions.txt"
# 		echo "***************************************************************************"
# 		[ $abort_on_fail -eq 1 ] && exit 1
# 	else
# 		echo "Package integrtity check looks good"
# 	fi
# 	/bin/rm $tmpfile
# fi


# Add git hooks as needed
cd $OPADM_REPO_ROOT/.git/hooks
[ -d ../../onprem_admin/hooks ] && hooksDir=../../onprem_admin/hooks || hooksDir=../../hooks
for hook in post-checkout post-merge post-rewrite
do
	echo -n "__ $hooksDir/$hook __"
	ln -snf $hooksDir/$hook
done
echo

# You must exit with a status of '0' if the script was successful or '1' otherwise.
exit 0
