
const Actions = {
	CONFIG_LOAD_NEW_CONFIG: 'CONFIG_LOAD_NEW_CONFIG',
	CONFIG_SET_DOTTED_PROPERTY: 'CONFIG_SET_DOTTED_PROPERTY',
	CONFIG_TOGGLE_DOTTED_BOOLEAN: 'CONFIG_TOGGLE_DOTTED_BOOLEAN',
	CONFIG_SET_SSL_PROPERTY: 'CONFIG_SET_SSL_PROPERTY',

	CONFIG_API_SERVER_SET_PHONEHOME_DISABLED: 'CONFIG_API_SERVER_SET_PHONEHOME_DISABLED',
	CONFIG_API_SERVER_SET_PUBLIC_API_URL: 'CONFIG_API_SERVER_SET_PUBLIC_API_URL',
	CONFIG_API_SERVER_SET_PORT: 'CONFIG_API_SERVER_SET_PORT',
	CONFIG_API_SERVER_SET_SECURE_PORT: 'CONFIG_API_SERVER_SET_SECURE_PORT',

	CONFIG_BROADCASTER_SET_PORT: 'CONFIG_BROADCASTER_SET_PORT',
	CONFIG_BROADCASTER_SET_SECURE_PORT: 'CONFIG_BROADCASTER_SET_SECURE_PORT',

	CONFIG_ADMIN_SET_PORT: 'CONFIG_ADMIN_SET_PORT',
	CONFIG_ADMIN_SET_SECURE_PORT: 'CONFIG_ADMIN_SET_SECURE_PORT',

	// CONFIG_EMAIL_NODEMAILER_DISABLED: 'CONFIG_EMAIL_NODEMAILER_DISABLED',
	// CONFIG_EMAIL_SENDGRID_DISABLED: 'CONFIG_EMAIL_SENDGRID_DISABLED',

	CONFIG_INTG_SLACK_APP_ID: 'CONFIG_INTG_SLACK_APP_ID',
	CONFIG_INTG_SLACK_CLIENT_ID: 'CONFIG_INTG_SLACK_CLIENT_ID',
	CONFIG_INTG_SLACK_CLIENT_SECRET: 'CONFIG_INTG_SLACK_CLIENT_SECRET',
	CONFIG_INTG_SLACK_SIGNING_SECRET: 'CONFIG_INTG_SLACK_SIGNING_SECRET',
	CONFIG_INTG_SLACK_INTERACTIVE_COMPONENTS: 'CONFIG_INTG_SLACK_INTERACTIVE_COMPONENTS',
	CONFIG_INTG_SLACK_DISABLED: 'CONFIG_INTG_SLACK_DISABLED',

	// CONFIG_SSLCERT_NEW_CERT: 'CONFIG_SSLCERT_NEW_CERT',
	CONFIG_SSLCERT_UPDATE_CERT: 'CONFIG_SSLCERT_UPDATE_CERT',
	CONFIG_SSLCERT_DELETE_CERT: 'CONFIG_SSLCERT_DELETE_CERT',

	// CONFIG_STORAGE_MONGO_SET_URL: 'CONFIG_STORAGE_MONGO_SET_URL',

	// CONFIG_: 'CONFIG_',
};

// Action Creators
export function togglePhoneHome() {
	console.debug('in togglePhoneHome action creator');
	return { type: Actions.CONFIG_API_SERVER_SET_PHONEHOME_DISABLED };
}

export function telemetryDataIsMissing(telemetry) {
	let answer = false;
	[
		['intercom.token', telemetry?.intercom?.token],
		['segment.token', telemetry?.segment?.token],
		['segment.webToken', telemetry?.segment?.webToken],
	].forEach((property) => {
		if (!property[1]) {
			console.warn(`${property[0]} missing from config`);
			answer = true;
		}
	});
	return answer;
}

// default export the apiServer actions
export default Actions;
