#!/bin/bash

[ -z "$2" ] && echo "Run dt-install-sandbox-software to call this script" && exit 1

# This script is called via the dt-install-sandbox-software command.
# Do not run it directly.  Further, this is called prior to the
# sandbox environment being loaded into the shell so any variables
# needed from the defaults.sh (or other env file) must be setup
# manually.

export CS_API_SANDBOX=$1  # root of the sandbox
export CS_API_TOP=$2      # root of the primary git project
SB_ENV_FILE=$3            # name of the environment file to use
export CS_API_NAME=`dirname $CS_API_SANDBOX`
[ -z "$SB_ENV_FILE" ] && SB_ENV_FILE=defaults.sh

# With the previous 3 variables defined, you can now load a defaults file if
# need be.
. $CS_API_TOP/sandbox/$SB_ENV_FILE


# Install additional git projects
# cd $CS_API_SANDBOX
# if [ ! -d cider_tools ]; then
# 	echo "Cloning cider_tools and installing node modules"
# 	origin_url=`(cd $CS_API_TOP && git config remote.origin.url)`
# 	if [ `echo $origin_url|grep -c http` -eq 1 ]; then
# 		tools_proj=https://github.com/pkt4dev/cider_tools
# 	else
# 		origin_proto=`echo $origin_url|cut -f1 -d:`
# 		tools_proj="$origin_proto:pkt4dev/cider_tools"
# 	fi
# 	echo "git clone $tools_proj"
# 	git clone $tools_proj
# else
# 	echo "cider_tools already exists. Not cloning"
# fiC


# Example code to fetch additional software needed for the sandbox and
# install it. Software is expected to be in the Sandbox Cloud. In this
# case we're install the mongodb binaries from a tarball.

# Install node if specified with CS_MAININ_NODE_VER
[ -n "$CS_API_NODE_VER" -a ! -L $CS_API_SANDBOX/node ] && dt-get-software -V $CS_MAININ_NODE_VER node $CS_API_SANDBOX

# Install yarn if specified with CS_MAININ_YARN_VER
[ -n "$CS_API_YARN_VER" -a ! -L $CS_API_SANDBOX/yarn ] && dt-get-software -V $CS_MAILIN_YARN_VER yarn $CS_API_SANDBOX


# Install secondary git repos
echo "Cloning TestRepo"
(cd $CS_API_SANDBOX && git clone git@github.com:teamcodestream/TestRepo) || exit 1

exit 0
